title: SCRIBE
description: Solutions, Conseils et Ressources pour l Informatique Bureautique
theme: just-the-docs

url: https://scribe-doc.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
