title: SCRIBE
description: Solutions, Conseils et Ressources pour l'Informatique BureautiquE
theme: just-the-docs

url: https://scribe-doc.github.io

defaults:
  -
    scope:
      path: 'admin/**'
    values:
      sitemap: false

exclude:
  - .obsidian
  - drafts
  - vendor

favicon_ico: "/favicon.ico"
logo: "/assets/images/logo.png"
lang: fr

plugins:
  - jekyll-sitemap

markdown: kramdown


#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
#color_scheme: dark-custom
color_scheme: light-custom


# footer_content: "..."
#last_edit_timestamp: true
last_edit_time_format: "%d/%m/%Y"



# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  tutoriels:
    #permalink: "/:collection/:path/"
    output: true
  pdf:
    output: true
  video:
    output: true
  suites-bureautiques:
    output: true


just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    pdf:
      name: "Documents PDF"
    suites-bureautiques:
      name: "Suites bureautiques, GED"
    video:
      name: "Vidéos"
    tutoriels:
      # Give the collection a name
      name: "Autres tutoriels"
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true


callouts:
  callout-warning:
    title: Attention
    color: red
  pj:
    color: blue
  callout-yellow:
    color: yellow
  cl-fct1:
    color: blue
  cl-info:
    color: purple


