title: SCRIBE
description: Solutions, Conseils et Ressources pour l'Informatique BureautiquE
theme: just-the-docs

url: https://scribe-doc.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
#color_scheme: dark-custom

favicon_ico: "/favicon.ico"
logo: "/assets/images/logo.png"

lang: fr

# footer_content: "..."
#last_edit_timestamp: true
last_edit_time_format: "%d/%m/%Y"

exclude:
  - .obsidian
  - drafts


